version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - wget https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip
      - unzip terraform_0.14.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform --version
      - terraform init 
      - terraform apply -var-file="./env/prod/prod.tfvars" -auto-approve